FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY . . 

 
RUN dotnet restore SescBaseApi.sln

# copy and publish app and libraries
COPY . .
RUN dotnet publish -c release -o /app  

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "Sesc.Base.Api.dll" ,"--urls", "http://*:5000;http://*:5001"]

EXPOSE 5000
Expose 5001